### ISSUE TITLE
Instant sign in when password reset

### ISSUE THREAD

**Issue by vreithinger** [supabase-community/flutter-auth-ui#36] opened 2023-01-10 15:41 UTC
# Bug report

## Describe the bug

In the example given clicking on password reset and entering an existing email, one is instantly logged in without having to click on the link in the email or entering any password.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Click on 'Forgot Password? Click here'
2. Type in email of existing account
3. Click on 'Send Reset Email'
=> One is logged in instantly

## Expected behavior

1. Click on 'Forgot Password? Click here'
2. Type in an existing email
3. Click on 'Send Reset Email'
4. Click on Link in Reset Email
5. Get redirected to Password Reset screen
6. Get signed in or get redirected to sign in screen to type in new password

**Comment by dippa-1** [comment] 2024-04-02 18:08
I can't reproduce this. Maybe you are already logged in? Can you try with logging out before?

**Comment by dshukertjr** [comment] 2024-05-13 06:25
I'm going to close this as Supabase does not have an option to sign-in with only an email address without clicking on the link. Agreeing with dippa-1 here, there might be a chance that you were already signed in.

**Closed by dshukertjr** 2024-05-13 06:25 UTC
Labels: bug
